"""Excel download (#77; ADR-0006 D8): one .xlsx written server-side by a
plain writer. Bound rows as a table, a second sheet with the generated
Office.js. Opens in Excel. Claims no chart it did not draw. Empty rows are
refused — not a fake workbook.
"""

from __future__ import annotations

import io
import zipfile
from typing import Any
from xml.etree import ElementTree

from fastapi.testclient import TestClient

from tests.conftest import SigningKeys, bearer_headers
from tests.test_charts import _upload_source

OFFICE_JS = (
    "async function renderFlintChart(context) {\n"
    "  const sheet = context.workbook.worksheets.getActiveWorksheet();\n"
    "  // generated by Flint — the host draws this, we do not.\n"
    "}\n"
)

ROWS = [
    {"quarter": "Q1", "revenue": 100},
    {"quarter": "Q2", "revenue": 200},
]


def _download(
    client: TestClient,
    signing: SigningKeys,
    *,
    rows: list[dict[str, Any]] = ROWS,
    office_js: str = OFFICE_JS,
) -> Any:
    return client.post(
        "/api/excel",
        json={"rows": rows, "office_js": office_js},
        headers=bearer_headers(signing),
    )


def _sheet_names(payload: bytes) -> list[str]:
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        workbook = archive.read("xl/workbook.xml")
    root = ElementTree.fromstring(workbook)
    ns = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
    return [sheet.attrib["name"] for sheet in root.findall(".//m:sheet", ns)]


def _shared_strings(payload: bytes) -> str:
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        try:
            raw = archive.read("xl/sharedStrings.xml")
        except KeyError:
            return ""
    return raw.decode("utf-8")


def _has_chart_part(payload: bytes) -> bool:
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        return any("chart" in name.lower() for name in archive.namelist())


def test_excel_workbook_is_rows_plus_office_js(
    db_client: TestClient, signing: SigningKeys
) -> None:
    response = _download(db_client, signing)
    assert response.status_code == 200
    assert (
        response.headers["content-type"]
        == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
    assert response.headers["content-disposition"].endswith('.xlsx"')
    payload = response.content
    assert payload[:2] == b"PK"  # a zip, i.e. a real workbook
    assert _sheet_names(payload) == ["Data", "Office.js"]
    strings = _shared_strings(payload)
    assert "Q1" in strings
    assert "Q2" in strings
    assert "quarter" in strings
    assert "revenue" in strings
    assert "renderFlintChart" in strings
    assert "the host draws this" in strings
    # The writer is a table plus the script — not a Python chart compiler.
    assert not _has_chart_part(payload)


def test_excel_empty_rows_are_refused_not_a_fake_workbook(
    db_client: TestClient, signing: SigningKeys
) -> None:
    response = _download(db_client, signing, rows=[])
    assert response.status_code == 422
    body = response.json()
    assert body["error"] == "excel_empty"
    assert response.headers.get("content-type", "").startswith("application/json")


def test_excel_blank_office_js_is_refused(
    db_client: TestClient, signing: SigningKeys
) -> None:
    response = _download(db_client, signing, office_js="   ")
    assert response.status_code == 422
    assert response.json()["error"] == "excel_empty"


def test_excel_never_crosses_an_owner_and_requires_auth(
    db_client: TestClient, signing: SigningKeys
) -> None:
    assert (
        db_client.post(
            "/api/excel", json={"rows": ROWS, "office_js": OFFICE_JS}
        ).status_code
        == 401
    )
    # Auth is the whole boundary — the route does not take a chart id, so
    # there is no other owner's workbook to steal. A signed-in caller may
    # download the rows they just bound.
    _upload_source(db_client, signing)  # the session is live
    assert _download(db_client, signing).status_code == 200
